<?php

namespace ContainerZrQTr2u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M3RLqABService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M3RLqAB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M3RLqAB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'planingRepository' => ['privates', 'App\\Repository\\PlaningRepository', 'getPlaningRepositoryService', true],
        ], [
            'planingRepository' => 'App\\Repository\\PlaningRepository',
        ]);
    }
}
