<?php

namespace ContainerZrQTr2u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecialityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BKGYMqa.App\Entity\Speciality' shared service.
     *
     * @return \App\Entity\Speciality
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BKGYMqa": it needs an instance of "App\\Entity\\Speciality" but this type has been excluded in "config/services.yaml".');
    }
}
