<?php

namespace ContainerCg1uZVu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zgsl1BvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zgsl1Bv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zgsl1Bv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'speciality' => ['privates', '.errored..service_locator.Zgsl1Bv.App\\Entity\\Speciality', NULL, 'Cannot autowire service ".service_locator.Zgsl1Bv": it needs an instance of "App\\Entity\\Speciality" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'speciality' => 'App\\Entity\\Speciality',
        ]);
    }
}
