<?php

namespace ContainerCg1uZVu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CnZk3WNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cnZk3WN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cnZk3WN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'planing' => ['privates', '.errored..service_locator.cnZk3WN.App\\Entity\\Planing', NULL, 'Cannot autowire service ".service_locator.cnZk3WN": it needs an instance of "App\\Entity\\Planing" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'planing' => 'App\\Entity\\Planing',
        ]);
    }
}
