<?php

namespace ContainerCg1uZVu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9K9MkFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9_K9MkF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9_K9MkF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dayWork' => ['privates', '.errored..service_locator.9_K9MkF.App\\Entity\\DayWork', NULL, 'Cannot autowire service ".service_locator.9_K9MkF": it needs an instance of "App\\Entity\\DayWork" but this type has been excluded in "config/services.yaml".'],
        ], [
            'dayWork' => 'App\\Entity\\DayWork',
        ]);
    }
}
