<?php

namespace ContainerCg1uZVu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DR1OeXMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dR1OeXM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dR1OeXM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctor' => ['privates', '.errored..service_locator.dR1OeXM.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.dR1OeXM": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'statuRepository' => ['privates', 'App\\Repository\\StatuRepository', 'getStatuRepositoryService', true],
        ], [
            'doctor' => 'App\\Entity\\User',
            'entityManager' => '?',
            'statuRepository' => 'App\\Repository\\StatuRepository',
        ]);
    }
}
