<?php

namespace ContainerCg1uZVu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SuO0Dv2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SuO0Dv2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SuO0Dv2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'planing' => ['privates', '.errored..service_locator.SuO0Dv2.App\\Entity\\Planing', NULL, 'Cannot autowire service ".service_locator.SuO0Dv2": it needs an instance of "App\\Entity\\Planing" but this type has been excluded in "config/services.yaml".'],
        ], [
            'planing' => 'App\\Entity\\Planing',
        ]);
    }
}
