<?php

namespace ContainerCg1uZVu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T8JquvQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T8JquvQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T8JquvQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'appointmentRepository' => ['privates', 'App\\Repository\\AppointmentRepository', 'getAppointmentRepositoryService', true],
            'statusController' => ['services', 'App\\Controller\\StatusController', 'getStatusControllerService', true],
        ], [
            'appointmentRepository' => 'App\\Repository\\AppointmentRepository',
            'statusController' => 'App\\Controller\\StatusController',
        ]);
    }
}
