<?php

namespace ContainerCg1uZVu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDayWork2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Eqbgb9x.App\Entity\DayWork' shared service.
     *
     * @return \App\Entity\DayWork
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Eqbgb9x": it needs an instance of "App\\Entity\\DayWork" but this type has been excluded in "config/services.yaml".');
    }
}
