<?php

namespace ContainerCg1uZVu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDayWorkTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\DayWorkType' shared autowired service.
     *
     * @return \App\Form\DayWorkType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DayWorkType.php';

        return $container->privates['App\\Form\\DayWorkType'] = new \App\Form\DayWorkType();
    }
}
