<?php

namespace ContainerCg1uZVu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoadStatusesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\LoadStatusesCommand' shared autowired service.
     *
     * @return \App\Command\LoadStatusesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/LoadStatusesCommand.php';

        $container->privates['App\\Command\\LoadStatusesCommand'] = $instance = new \App\Command\LoadStatusesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('load-statu');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
