<?php

namespace ContainerCg1uZVu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaningService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SuO0Dv2.App\Entity\Planing' shared service.
     *
     * @return \App\Entity\Planing
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SuO0Dv2": it needs an instance of "App\\Entity\\Planing" but this type has been excluded in "config/services.yaml".');
    }
}
