<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX5hYzGw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX5hYzGw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX5hYzGw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX5hYzGw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX5hYzGw\App_KernelDevDebugContainer([
    'container.build_hash' => 'X5hYzGw',
    'container.build_id' => '73cf9ac3',
    'container.build_time' => 1718271095,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX5hYzGw');
