<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxNiEKq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxNiEKq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxNiEKq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxNiEKq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOxNiEKq\App_KernelDevDebugContainer([
    'container.build_hash' => 'OxNiEKq',
    'container.build_id' => 'd8e9f172',
    'container.build_time' => 1718024589,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxNiEKq');
