<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCg1uZVu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCg1uZVu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCg1uZVu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCg1uZVu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCg1uZVu\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cg1uZVu',
    'container.build_id' => 'da5cb60b',
    'container.build_time' => 1716809699,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCg1uZVu');
